### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by djut28** [JelteMX/mendix-tree-view#6]
@JelteMX Is there a possibility to select a node by guid or something like this? It would be a very nice feature.
Something like this is implemented in the treetable but not in the treeview.
Thanks in advance

**Comment by djut28** [comment]
Hey @JelteMX do you think there will be an update in the next time?

**Comment by JelteMX** [comment]
Same functionality as described [here](https://github.com/JelteMX/mendix-tree-table#9-misc) has been implemented now in [1.4.0](https://github.com/JelteMX/mendix-tree-view/releases/tag/1.4.0) of Tree View.
